include_directories(${PROJECT_SOURCE_DIR}/../deps/uv/include)
include_directories(${PROJECT_SOURCE_DIR}/../deps/uv/include/*)
include_directories(${PROJECT_SOURCE_DIR}/../deps/uv/src)
include_directories(${PROJECT_SOURCE_DIR}/../deps/uv/src/*)
file(GLOB uv_headers ${PROJECT_SOURCE_DIR}/../deps/uv/include/*)
file(GLOB uv_headers ${PROJECT_SOURCE_DIR}/../deps/uv/include/*)
file(GLOB uv_sources ${PROJECT_SOURCE_DIR}/../deps/uv/src/*)
source_group(deps\\uv\\include FILES ${uv_headers})
source_group(deps\\uv\\src FILES ${uv_sources})
